### PR TITLE
add upvoting and downvoting articles and code clean up

### PR DESCRIPTION
**Pull request by wbaig2**

### CODE REVIEW

**Comment by cjplatten** [comment]
There is an error in the console that needs addressing and it woud be good if the cursor changed to a pointer for the interactive parts of your app for accessibility - right now it's not obvious what is clickable.

Other that that this looks good to go!

**Comment by wbaig2** [comment]
Thanks Carrie - the cursor change is in my media query.  It only changes to a pointer when the screen width is more than a certain amount, due to the CSS being for mobile first :)

**Comment by cjplatten** [comment]
> Thanks Carrie - the cursor change is in my media query. It only changes to a pointer when the screen width is more than a certain amount, due to the CSS being for mobile first :)

Desktop windows can still be a narrower width so it's still worth having the cursor change!

**Comment by wbaig2** [comment]
Noted!

**Pull request merged**
